from fastapi import HTTPException
PROJECT = {
 "DRAFT": {"PENDING_REVIEW"}, "PENDING_REVIEW": {"PUBLISHED", "CANCELLED"},
 "PUBLISHED": {"RECEIVING_PROPOSALS"}, "RECEIVING_PROPOSALS": {"PROVIDER_SELECTED", "CANCELLED"},
 "PROVIDER_SELECTED": {"CONNECTION_PENDING", "RECEIVING_PROPOSALS"},
 "CONNECTION_PENDING": {"PAYMENT_PENDING", "RECEIVING_PROPOSALS"},
 "PAYMENT_PENDING": {"PAYMENT_APPROVED", "PAYMENT_REJECTED", "RECEIVING_PROPOSALS"},
 "PAYMENT_REJECTED": {"PAYMENT_PENDING", "RECEIVING_PROPOSALS"},
 "PAYMENT_APPROVED": {"CONTRACT_PENDING"}, "CONTRACT_PENDING": {"CONTRACT_REVIEW", "RECEIVING_PROPOSALS"},
 "CONTRACT_REVIEW": {"CONTRACT_PENDING", "IN_PROGRESS"}, "IN_PROGRESS": {"COMPLETION_PENDING"},
 "COMPLETION_PENDING": {"COMPLETED", "IN_PROGRESS"}, "COMPLETED": set(), "CANCELLED": set(),
}
def move(project, new: str):
    if new not in PROJECT.get(project.status, set()):
        raise HTTPException(409, f"انتقال وضعیت {project.status} به {new} مجاز نیست")
    project.status = new
